### ISSUE TITLE
supplied key param cannot be coerced into a private key

### ISSUE THREAD

**Issue by gaurav2262** [keithbrink/walmart-marketplace-laravel-sdk#2]
Hello @keithbrink ,

Thanks for this code, but I'm facing some problem while calling **orderGet**,
Here is my code 

> WalmartMkt::orderGet()->all(Carbon::now(),Carbon::now()->subDays(40))

When I'm running this code it throws an error like `openssl_sign(): supplied key param cannot be coerced into a private key`

Can you please help me to figure out this error.

Thanks,

**Comment by keithbrink** [comment]
Sorry, not sure.
